day17/urls.py
from django.contrib import admin
from django.urls import path
from app.views import department, user, pretty, admin, account, task, upload

urlpatterns = [
    path('test/', department.test),
    path('depart/list/', department.depart_list),
    path('depart/add/', department.depart_add),
    path('depart/delete/', department.depart_delete),
    path('depart/<int:nid>/edit/', department.depart_edit),

    path('user/list/', user.user_list),
    path('user/add/', user.user_add),
    path('user/add/form/add/', user.user_add_form_add),
    path('user/<int:nid>/edit/', user.user_edit),
    path('user/<int:nid>/delete/', user.user_delete),

    path('pretty/list/', pretty.pretty_list),
    path('pretty/add/', pretty.pretty_add),
    path('pretty/<int:nid>/edit/', pretty.pretty_edit),
    path('pretty/<int:nid>/delete/', pretty.pretty_delete),

    path('admin/list/', admin.admin_list),
    path('admin/add/', admin.admin_add),
    path('admin/<int:nid>/edit/', admin.admin_edit),
    path('admin/<int:nid>/delete/', admin.admin_delete),
    path('admin/<int:nid>/reset/', admin.admin_reset),

    path('',account.login),
    path('login/', account.login),
    path('logout/', account.logout),
    path('image/code/', account.image_code),

    path('task/list/', task.task_list),
    path('task/test/', task.task_test),
    path('task/add/', task.task_add),

    path('upload/list/', upload.upload_list),
    path('upload/multi/', upload.upload_multi),


]

app/models.py
from django.db import models


# Create your models here.
class Department(models.Model):
    """部门表"""
    # id 自动生成
    title = models.CharField(verbose_name='部门表', max_length=32)

    def __str__(self):
        return self.title


class UserInfo(models.Model):
    """用户表"""
    name = models.CharField(verbose_name='姓名', max_length=16)
    password = models.CharField(verbose_name='密码', max_length=64)
    age = models.IntegerField(verbose_name='年龄')
    account = models.DecimalField(verbose_name='账户余额', max_digits=10,
                                  decimal_places=2,
                                  default=0)
    create_time = models.DateField(verbose_name='入职时间')
    # 1.无约束
    # d_id = models.BigAutoField(verbose_name='部门ID')
    # 2.有约束
    # django自动
    # -写的depart
    # -生成数据列depart_id
    # 3.部门表被删除（默认需要先删除父表）
    # 3.1级联删除
    # depart = models.ForeignKey(to='Department',to_field='id',on_delete=models.CASCADE)
    # 3.2置空（这种情况要加上可为空）
    depart = models.ForeignKey(verbose_name='部门名称', to='Department', to_field='id',
                               null=True, blank=True,
                               on_delete=models.SET_NULL)
    # 性别没有必要再新建一个表，不会动态增加,可以使用1/2存储来减小数据库存储空间
    # 在django中约束
    gender_choice = (
        (1, '男'),
        (2, '女')
    )
    # 在数据库中的约束
    gender = models.SmallIntegerField(verbose_name='性别', choices=gender_choice)


class PrettyNum(models.Model):
    """靓号表"""
    mobile = models.CharField(verbose_name='手机号', max_length=11)
    price = models.IntegerField(verbose_name='价格', default=0)
    level_choices = (
        (1, '一级'),
        (2, '二级'),
        (3, '三级'),
        (4, '四级'),
        (5, '五级'),
    )
    level = models.SmallIntegerField(verbose_name='级别', choices=level_choices,
                                     default=1)
    status_choices = (
        (1, '已占用'),
        (2, '未占用'),
    )
    status = models.SmallIntegerField(verbose_name='状态', choices=status_choices,
                                      default=2)


class Admin(models.Model):
    """管理员"""
    username = models.CharField(verbose_name='管理员名称', max_length=32)
    password = models.CharField(verbose_name='密码', max_length=64)

    def __str__(self):
        return self.username


class Account(models.Model):
    """登录数据"""
    username = models.CharField(verbose_name='用户名', max_length=32)
    password = models.CharField(verbose_name='密码', max_length=64)


class Task(models.Model):
    """任务"""
    level_choice = (
        (1, '紧急'),
        (1, '重要'),
        (1, '临时'),
    )

    level = models.SmallIntegerField(verbose_name='级别', choices=level_choice, default=1)
    title = models.CharField(verbose_name='标题', max_length=64)
    detail = models.TextField(verbose_name='详细信息')
    user = models.ForeignKey(verbose_name='负责人', to='Admin', on_delete=models.CASCADE)

app/templates/admin_edit.html
{% extends 'layout.html' %}

{% block content %}

    <div class="panel panel-default">
        <div class="panel-heading">编辑管理员</div>

        <div class="panel-body">
            <form method="post" novalidate>
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <label class="col-sm-2 control-label">
                            {{ field.label }}</label>
                        {{ field }}
                        <span style="color: red">{{ field.errors }}</span>
                    </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>



{% endblock %}

app/templates/admin_reset.html
{% extends 'layout.html' %}

{% block content %}

    <div class="panel panel-default">
        <div class="panel-heading">编辑管理员</div>

        <div class="panel-body">
            <form method="post" novalidate>
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <label class="col-sm-2 control-label">
                            {{ field.label }}</label>
                        {{ field }}
                        <span style="color: red">{{ field.errors }}</span>
                    </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>



{% endblock %}

app/templates/depart_add.html
{% extends 'layout.html' %}
{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">新建部门</div>

        <div class="panel-body">
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="exampleInputEmail1">新建部门</label>
                    <input type="text" class="form-control" name="title">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>



{% endblock %}

app/templates/depart_edit.html
{% extends 'layout.html' %}
{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">编辑部门</div>

        <div class="panel-body">
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="exampleInputEmail1">编辑部门</label>
                    <input type="text" class="form-control" placeholder="
{{ data_list.title }}"
                           name="title">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>




{% endblock %}

app/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="
{% static 'plugins/bootstrap-3.4.1/css/bootstrap.css' %}">
    <style>
        .navbar {
            border-radius: 0;
        }
    </style>
    {% block css %}{% endblock %}
</head>
<body>

<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1"
                    aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">联通用户管理系统</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="/depart/list/">部门管理</a></li>
                <li><a href="/user/list/">用户管理</a></li>
                <li><a href="/pretty/list/">靓号管理</a></li>
                <li><a href="/admin/list/">管理员管理</a></li>
                <li><a href="/task/list/">任务管理</a></li>
                <li><a href="/upload/list/">文件上传</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">


                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                       role="button" aria-haspopup="true"
                       aria-expanded="false">{{ request.session.info.name }}
                        <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">个人资料</a></li>
                        <li><a href="#">我的信息</a></li>
                        <li><a href="#">主页</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="/logout/">注销</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    <!-- 其他的都不用写，只需要写block部分 -->
    {% block content %}

    {% endblock %}
</div>


<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>

{% block js %}{% endblock %}
</body>
</html>

app/templates/pretty_add.html
{% extends 'layout.html' %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">新建靓号</div>

        <div class="panel-body">
            <form method="post" novalidate>
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <label class="col-sm-2 control-label">
                            {{ field.label }}</label>
                        {{ field }}
                        <span style="color: red">{{ field.errors }}</span>
                    </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>



{% endblock %}

app/templates/pretty_edit.html
{% extends 'layout.html' %}
{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">编辑靓号</div>

        <div class="panel-body">
            <form method="post" novalidate>
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <label class="col-sm-2 control-label">
                            {{ field.label }}</label>
                        {{ field }}
                        <span style="color: red">{{ field.errors }}</span>
                    </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>



{% endblock %}

app/templates/pretty_list.html
{% extends 'layout.html' %}
{% block content %}
    <div>
        <a class="btn btn-success" href="/pretty/add/">靓号管理</a>

        <div style="float:right; width: 300px">
            <form method="get">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for..."
                           name="q" value="{{ search_data }}">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">
                            <span class="glyphicon glyphicon-search"
                                  aria-hidden="true"></span>
                        </button>
                    </span>

                </div>
            </form>
        </div>
    </div>
    <div class="panel panel-default" style="margin-top: 10px">
        <!-- Default panel contents -->
        <div class="panel-heading"><span class="glyphicon glyphicon-th-list"
                                         aria-hidden="true"></span> 靓号列表
        </div>

        <!-- Table -->
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>ID</th>
                <th>号码</th>
                <th>价格</th>
                <th>级别</th>
                <th>状态</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for obj in data_list %}
                <tr>
                    <th scope="row">{{ obj.id }}</th>
                    <td>{{ obj.mobile }}</td>
                    <td>{{ obj.price }}</td>
                    <td>{{ obj.get_level_display }}</td>
                    <td>{{ obj.get_status_display }}</td>
                    <td>
                        <a class="btn btn-xs btn-success" href="/pretty/
{{ obj.id }}/edit/">编辑</a>
                        <a class="btn btn-xs btn-danger" href="/pretty/
{{ obj.id }}/delete/">删除</a>
                    </td>
                </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>


    <nav aria-label="Page navigation" style="display: inline-block">
        <ul class="pagination">
            {{ page_string }}
        </ul>
    </nav>


{% endblock %}

app/templates/task_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">表单</div>
            <div class="panel-body">

                <form id="formAdd">

                    <div class="clearfix">
                        {% for field in form %}
                            <div class="col-xs-6">
                                <div class="form-group" style="position: relative;margin-bottom: 20px;">
                                    <label>{{ field.label }}</label>
                                    {{ field }}
                                    <span class="error-msg" style="color: red;position: absolute;"></span>
                                </div>
                            </div>
                        {% endfor %}
                        <div class="col-xs-12">
                            <button id="btnAdd" type="button" class="btn btn-primary">提 交</button>
                        </div>
                    </div>

                </form>


            </div>
        </div>
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                任务列表
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>标题</th>
                    <th>级别</th>
                    <th>负责人</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <th>{{ obj.id }}</th>
                        <td>{{ obj.title }}</td>
                        <td>{{ obj.get_level_display }}</td>
                        <td>{{ obj.user.username }}</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="#">编辑</a>
                            <a class="btn btn-danger btn-xs" href="#">删除</a>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
        <ul class="pagination">
            {{ page_string }}
        </ul>

        <div style="height: 1000px"></div>
        <hr/>
        <div>
            <h1>Ajax学习</h1>
            <h3>示例1</h3>
            <input id="btn1" type="button" class="btn btn-primary" value="点击1"/>

            <h3>示例2</h3>
            <input type="text" id="txtUser" placeholder="姓名"/>
            <input type="text" id="txtAge" placeholder="年龄"/>
            <input id="btn2" type="button" class="btn btn-primary" value="点击2"/>

            <h3>示例3</h3>
            <form id="form3">
                <input type="text" name="user" placeholder="姓名"/>
                <input type="text" name="age" placeholder="年龄"/>
                <input type="text" name="email" placeholder="邮箱"/>
                <input type="text" name="more" placeholder="介绍"/>
            </form>
            <input id="btn3" type="button" class="btn btn-primary" value="点击3"/>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript">
        $(function () {
            // 页面框架加载完成之后代码自动执行
            bindBtn1Event();

            bindBtn2Event();

            bindBtn3Event();

            bindBtnAddEvent();

        })

        function bindBtn1Event() {
            $("#btn1").click(function () {
                $.ajax({
                    url: '/task/test/',
                    type: "post",
                    data: {
                        n1: 123,
                        n2: 456
                    },
                    dataType: "JSON",
                    success: function (res) {
                        console.log(res);
                        console.log(res.status);
                        console.log(res.data);
                    }
                })
            })
        }

        function bindBtn2Event() {
            $("#btn2").click(function () {
                $.ajax({
                    url: '/task/test/',
                    type: "post",
                    data: {
                        name: $("#txtUser").val(),
                        age: $("#txtAge").val()
                    },
                    dataType: "JSON",
                    success: function (res) {
                        console.log(res);
                        console.log(res.status);
                        console.log(res.data);
                    }
                })
            })
        }

        function bindBtn3Event() {
            $("#btn3").click(function () {
                $.ajax({
                    url: '/task/test/',
                    type: "post",
                    data: $("#form3").serialize(),
                    dataType: "JSON",
                    success: function (res) {
                        console.log(res);
                        console.log(res.status);
                        console.log(res.data);
                    }
                })
            })
        }

        function bindBtnAddEvent() {
            $("#btnAdd").click(function () {
                $(".error-msg").empty();
                $.ajax({
                    url: '/task/add/',
                    type: "post",
                    data: $("#formAdd").serialize(),
                    dataType: "JSON",
                    success: function (res) {
                        if (res.status) {
                            alert("添加成功");
                            // 用JS实现页面的刷新
                            location.reload();
                        } else {
                            $.each(res.error, function (name, data) {
                                // console.log(name,data);
                                $("#id_" + name).next().text(data[0]);
                            })
                        }
                    }
                })
            })
        }

    </script>
{% endblock %}

app/templates/upload_list.html
{% extends 'layout.html' %}

{% block content %}

    <div class="panel panel-default">
        <div class="panel-heading">上传文件</div>
        <div class="panel-body">

            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="text" name='username'/>
                <input type="file" name='avatar'/>
                <input type="submit" value="提交"/>

            </form>


        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">批量上传文件</div>
        <div class="panel-body">

            <form method="post" enctype="multipart/form-data" action="/upload/multi/">
                {% csrf_token %}
                <input type="text" name='username'/>
                <input type="file" name='excel'/>
                <input type="submit" style="margin-top: 10px" value="上传"/>

            </form>


        </div>
    </div>

{% endblock %}

app/templates/user_add.html
{% extends 'layout.html' %}

{% load static %}
{% block css %}
    <link rel="stylesheet" href="
{% static 'plugins/bootstrap-datepicker/css/datepicker.css' %}">
{% endblock %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">新建用户</div>

        <div class="panel-body">
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="exampleInputEmail1">用户姓名</label>
                    <input type="text" class="form-control" name="name">
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">年龄</label>
                    <input type="text" class="form-control" name="title">
                </div>
                <div class="form-group">
                    <select>
                        {% for obj in gender_choices %}
                            <option value="{{ obj.0 }}">{{ obj.1 }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">部门</label>
                    <select>
                        {% for obj in depart_list %}
                            <option value='{{ obj.id }}'>{{ obj.title }}</option>
                        {% endfor %}
                    </select>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>



{% endblock %}

{% block js %}
    <script src="{% static 'plugins/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>
{% endblock %}

app/templates/user_edit.html
{% extends 'layout.html' %}
{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">编辑用户</div>

        <div class="panel-body">
            <form method="post" novalidate>
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <label class="col-sm-2 control-label">
                            {{ field.label }}</label>
                        {{ field }}
                        <span style="color: red">{{ field.errors }}</span>
                    </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>



{% endblock %}

app/templates/user_list.html
{% extends 'layout.html' %}
{% block content %}
    <div>
        <a class="btn btn-success" href="/user/add/">新建用户</a>
        <a class="btn btn-success" href="/user/add/form/add/">新建用户modelform</a>
    </div>
    <div class="panel panel-default"  style="margin-top: 10px">
        <!-- Default panel contents -->
        <div class="panel-heading"><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
            用户列表</div>

        <!-- Table -->
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>用户ID</th>
                <th>名称</th>
                <th>年龄</th>
                <th>余额</th>
                <th>密码</th>
                <th>性别</th>
                <th>入职时间</th>
                <th>部门名称</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for obj in data_list %}
            <tr>
                <th scope="row">{{ obj.id }}</th>
                <td>{{ obj.name }}</td>
                <td>{{ obj.age }}</td>
                <td>{{ obj.account }}</td>
                <td>{{ obj.password }}</td>
                <td>{{ obj.get_gender_display }}</td>
                <td>{{ obj.create_time|date:"y-m-d" }}</td>
                <td>{{ obj.depart.title }}</td>
                <td>
                    <a class="btn btn-xs btn-success" href="/user/
{{ obj.id }}/edit/">编辑</a>
                    <a class="btn btn-xs btn-danger" href="/user/
{{ obj.id }}/delete/">删除</a>
                </td>
            </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>

    <ul class="pagination">
        {{ page_string }}
    </ul>
{% endblock %}

app/templates/user_model_form_add.html
{% extends 'layout.html' %}

{% load static %}
{% block css %}
    <link rel="stylesheet" href="
{% static 'plugins/bootstrap-datepicker/css/datepicker.css' %}">
{% endblock %}


{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">新建用户</div>

        <div class="panel-body">
            <form method="post" novalidate>
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <label class="col-sm-2 control-label">
                            {{ field.label }}</label>
                        {{ field }}
                        <span style="color: red">{{ field.errors }}</span>
                    </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>



{% endblock %}

{% block js %}
    <script src="{% static 'plugins/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-datepicker/js/locales/bootstrap-datepicker.zh-CN.js' %}"></script>
    <script>
        $(function () {
            $('#id_create_time').datepicker({
                format: 'yyyy-mm-dd',
                startDate: '1999-01-01',
                language: 'zh-CN',
                autoclose: true
            });
        })
    </script>
{% endblock %}